<?php
/**
 * 标签钩子 — 入口渲染函数
 * 注入 serveFrontend() 流程，在 echo 之前解析标签
 */
class TagHook
{
    /**
     * 渲染模板中的标签
     *
     * @param  string $html       模板 HTML 源码
     * @param  string $filePath   模板文件路径（用于缓存 key）
     * @return string 渲染后的 HTML
     */
    public static function render($html, $filePath)
    {
        // 无标签则跳过
        if (strpos($html, '[--') === false) {
            return $html;
        }

        try {
            // 检查缓存
            $cached = TagCache::get($filePath);
            if ($cached !== null) {
                return self::executeCached($cached);
            }

            // 编译
            $tokens = TagParser::tokenize($html);
            $ast    = TagParser::buildAST($tokens);
            $code   = TagCompiler::compile($ast['nodes']);

            // 包装为可执行函数
            $wrapped = "<?php\n" .
                       "// Auto-generated by TagHook. Do not edit.\n" .
                       "// Source: {$filePath}\n" .
                       "// Generated: " . date('Y-m-d H:i:s') . "\n\n" .
                       "defined('DB_HOST') or die('Access denied');\n\n" .
                       $code;

            // 写入缓存
            TagCache::set($filePath, $wrapped);

            return self::executeCached($wrapped);
        } catch (Exception $e) {
            error_log('TagHook render error: ' . $e->getMessage());
            // 降级：返回原始 HTML，去掉未解析的标签
            return preg_replace('/\[--.*?--\]/', '', $html);
        }
    }

    /**
     * 执行缓存中的 PHP 代码并捕获输出
     *
     * @param  string $code PHP 源码
     * @return string 执行输出
     */
    private static function executeCached($code)
    {
        ob_start();
        eval('?>' . $code);
        return ob_get_clean();
    }
}
